# -*- coding: utf-8 -*-
"""hello.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rk7qWcbd1y-VWpx8581X0Bawt6bxLgDK
"""

import streamlit as st
st.write('Hello, World! : sunglasses:')